### ISSUE TITLE
Editing layers dialog should be based on layers title and not on the shortname

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client-plugin-editing#18]
## Original source: https://github.com/g3w-suite/g3w-client/issues/40#issuecomment-1156429281

> IMHO Editing layers dialog should be based on layers title and not on the shortname
>
> Is this intended?
>
> I have the ``cona`` shortname displayed instead of the title of the layer ``water pipes``.
>
> <img width="341" alt="image" src="https://user-images.githubusercontent.com/3179646/173830196-a5f25f5c-4704-4925-a209-06e644cf8bf7.png">

**Comment by volterra79** [comment]
@Raruto are you sure? It should be referred to `layer.name`

**Comment by Raruto** [comment]
@volterra79 haven't tested it, reported here to keep a track of it

@tudorbarascu if you could provide a public link that replicate this issue we would appreciate it 😋

**Comment by tudorbarascu** [comment]
https://g3w.qtibia.ro/en/map/grup-urbanism/qdjango/1/ user: demo password: g3wrocks


It's easy replicable on your demo data project:

1. You go to buildings layer properties and put any shortname (example: bu) like in the following image
![pic](https://user-images.githubusercontent.com/3179646/225366502-10d2c0d5-afe8-4243-9084-aaab1dc7d377.jpeg)
2. Save the project and upload it.
3. You'll see that in editing the layer name is **bu** instead of **buildings**; same for when opening the attribute table.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/3179646/225368510-f4423f60-2b4e-4fa9-a802-3c0c3c9b8978.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/3179646/225368835-eeba704b-c839-4f41-8038-5bd290efba1a.png">

Thanks!
